language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - mysql -e 'create database turnera_test;'
  - sh -c "./bin/cake Migrations migrate"

script:
  - phpunit

notifications:
  email: true
