language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --require-dev
  - mysql -e 'create database turnera_test;'
  - sh -c "./bin/cake Migrations migrate"

after_script:
  - php vendor/bin/coveralls

notifications:
  email: true
